<?php 

define('menu','Menu');
define('index_inicio','Home');
define('index_campeonato','Championship');
define('index_reglamento','Rules');
define('index_registro','Register');
define('index_solistas','Soloists');
define('index_parejas','Couples');
define('index_grupos','Teams');
define('index_envianostufoto','Send your photo');
define('index_lineup','Line Up');
define('index_comprartickets','Get tickets/Buy tickets');
define('index_contactoviawhatsapp','Whatsapp Contact');
define('index_eurosonlatinopresenta','Euroson Latino presents');
define('index_fechaevento','December 6-11, 2021');
define('index_competencias_shows_workshops','World Championship | Intl. Shows | Workshops | Concerts | Salsa & Bachata Social Parties');
define('index_transmision_en_vivo','Grand Oasis Cancún - México');
define('index_se_parte_de_la_historia','Come & Be part of the history!');
define('index_cuentaregresiva','Countdown');
define('index_ver_mas','See more');
define('index_workshops','Workshops');
define('index_fullpass','Full Pass');
define('index_nightpass','Night Pass');
define('index_10_workshops','Workshops');
define('index_6_dias_competencia','Competition days');
define('index_comprar_ticket','Buy ticket');
define('index_apartar_ticket','Save ticket');
define('index_todos_los_derechos_reservados','Copyright');
define('index_registro_solistas','Soloists Register');
define('index_nombre','First Name');
define('index_ingresa_tu_nombre','Enter your name');
define('index_apellidos','Last Name');
define('index_ingresa_tus_apellidos','Enter your last name');
define('index_hotelnum','Reservation Code - Hotel');
define('index_ingresa_hotelnum','Enter your reservation code');
define('index_correo_electronico','Email');
define('index_ingresa_tu_correo_electronico','Enter your email');
define('index_fecha_de_nacimiento','Date of birth');
define('index_genero','Gender');
define('index_masculino','Male');
define('index_femenino','Female');
define('index_pais','Country');
define('index_seleccione_su_pais','Select your country');
define('index_categoria','Division');
define('index_subtotal','Subtotal');
define('index_descuento','Discount');
define('index_impuestos','Tax');
define('index_total','Total');
define('index_metodo_de_pago','Payment method');
define('index_pago','Pay');
define('index_ya_realizaste_tu_pago','Bank transfer pay?');
define('index_ingrese_su_id_de_transaccion','Enter your Reference id, bank authorization number');
define('index_enviar_registro','Send your register');
define('index_informacion_competidor','Information competitor');
define('index_informacion_general','General information');
define('index_nombre_del_grupo','Team Name');
define('index_nombre_del_representante','Couch Name');
define('index_no_telefonico','Phone Number');
define('index_no_de_integrantes','No. Integrantes');
define('index_informacion_de_integrantes','Members information');
define('index_todas_las_fotografias_enviadas','All banners sent will be uploaded at <a href="https://facebook.com/eurosonlatino" target="_blank"> Facebook (Euroson Latino World Salsa Championship)</a>');
define('index_codigo_de_inscripcion','Inscription Code');
define('index_tipo_de_categoria','Division Type');
define('index_arrastra_y_suleta_aqui_tu_archivo_para_subir','Drag & drop your file to upload');
define('index_o_selecciona_tu_archivo','Or browse your file');
define('index_nota_importante_el_codigo_de_inscripcion',"You must have received your register code via email after registering. If you haven't received it and you've already paid, contact us: info@eurosonlatino.com.mx or whatsapp.");
define('index_enviar_imagen','Send image');
define('index_programa','Schedule');
define('index_y','&');
define('index_dias','Days');
define('index_horas','Hours');
define('index_mins','Mins');
define('index_segs','Secs');
define('index_ingresar_nombre_grupo',"Enter the group's name");
define('index_invitados_internacionales','International guests');
define('index_tiene_cupon','Have a discount cupon?');
define('index_agregar_cupon','Click to enter cupon');
define('index_informacion_adicional','Additional information');
define('index_notas_de_orden','Order notes');
define('index_placeholder_notas_orden','Additional notes about your request.');
define('index_comprar','Buy');
define('index_alert_success_registro',"<p class='card-text font-size-sm'>You will briefly receive an email containing register details. Do not forget to verify the spam or others (Outlook). </p> <p class='card-text font-size-sm'><strong>If you don't receive with in 48 hrs after purchasing, verify ths spam or other (Outlook).</strong></p><p class='card-text font-size-sm'> In Case you don't receive it, please email us at <a href='mailto:info@eurosonlatino.com.mx'>info@eurosonlatino.com.mx</a></p>");
define('index_alert_success_imagenenviada','Image delivery done successfully');
define('index_placeholder_ingresa_codinsc','Enter your Inscription Code');
define('index_notaimportante','Important Note');
define('index_texto_formenviarfoto',"You must have received your register code via email after registering. If you haven't received it and you've already paid, contact us: <a href='mailto:info@eurosonlatino.com.mx'>info@eurosonlatino.com.mx</a> or <a target='_blank' class='text-warning' href='https://api.whatsapp.com/send?phone=522222501558&text=Hola%2C%20necesito%20mas%20informaci%C3%B3n.'>Whatsapp</a>");
define('index_envianostufoto_menu','Send your photo');
define('index_codigocupon','Coupon');
define('index_realizar_pago','Pay now');
define('index_terminos_condiciones','I agree to the <a href="https://bit.ly/terminos-y-condiciones-euroson-latino" target="_blank">Terms and conditions</>');
define('index_aceptar_terminos_y_condiciones','You must agree before submitting.');
define('index_seleccione_su_categoria','Select your category');
define('index_redireccion','<span class="text-muted font-size-xs">This page will be redirect in <span id="testdiv"></span> seconds</span>');
define('index_codigoincorrecto','Inscription Code incorrect, please check your information');
define('index_problemas_contactanos','If you have a problem, please contact us <a class="text-dark" href="mailto:info@eurosonlatino.com.mx" target="_blank">info@eurosonlatino.com.mx</a> or Whatsapp click <a target="_blank" class="text-dark" href="https://api.whatsapp.com/send?phone=522222501558&text=Hola%2C%20necesito%20mas%20informaci%C3%B3n.">here</a>');
define('index_cuponpromocional','Promo code');
define('index_aplicarcodigo','Apply code');
define('index_ingresa_tu_codigo','Enter your code');
define('index_campo_requerido','Required field');
define('index_seleccione_una_opcion','Select a option');
define('index_details','Details');
define('index_backgroundhome','bg-header-en');
define('index_detalles_registro','Register details');
define('index_horariolocal','Local Time - Mexico City');
define('index_diciembre','Dec');
define('index_resultados','Scores');
define('index_lunes','Monday 14');
define('index_martes','Tuesday 15');
define('index_miercoles','Wesdnesday 16');
define('index_jueves','Thursday 17');
define('index_viernes','Friday 18');
define('index_apartado_fullpass', 'Save your Full Pass');
define('index_apartado_nightpass', 'Save your Night Pass');
define('index_tickets','Tickets');
define('index_info_fullpass','Full Pass Information');
define('index_selecionar','Select');
define('index_mensaje_asistentes', '<h4><strong><span class="text-danger">Important Note:</span></strong>All those attending the Euroson Latino 2023 must be staying at the Hotel Grand Oasis Cancun, since by hotel policy the use of the facilities will not be allowed to outsiders.</h4>');
define('index_mensaje_asistentes_2','<strong><span class="text-danger">Important Note:</span></strong>All those attending the Euroson Latino 2023 must be staying at the Hotel Grand Oasis Cancun, since by hotel policy the use of the facilities will not be allowed to outsiders.</h4>');
define('index_liquida_pase', 'Pay off your Pass');
define('index_ingresa_codconfirmacion', 'Enter your Invoice id');
define('index_validar_codigo','Validate code');
define('index_slide_0','slide-main-0-en.jpg');
define('index_slide_1','slide-main-1-en.jpg');
define('index_slide_2','slide-main-2-en.jpg');
define('index_registroreservacion','Reservation Register');
define('index_fecha_entrada','Check In');
define('index_fecha_salida','Check Out');
define('index_num_habitaciones', 'Rooms');
define('index_num_huespedes', 'Guests');
define('index_adjuntar_comprobante', 'Attach hotel receipt');
define('index_mensaje_input_comprobante', 'Please attach your hotel receipt');
define('index_adjuntar_archivo', 'Attach file');
define('index_mensaje_input_archivo', 'Please attach your file');
define('index_conciertos','Concerts');
define('index_codconfirmfullpass', 'Full Pass - Code Confirmation');
define('index_ingresacodconfirmfullpass', 'Enter your Full Pass Code Confirmation');
define('index_infoapartado', 'Info - Ticket Save');
define('index_nombrecompleto', 'Full Name');
define('index_expositores','Expositores');
define('index_desc_fullpass', 'World Championship, International Shows, Workshops, Concerts, Salsa, Bachata & Kizomba Social, After Parties, Beach Club');
define('index_desc_nightpass', 'World Championship, International Shows, Concerts, Salsa, Bachata & Kizomba Social, After Parties, Beach Club');
define('index_registro_cerrado', 'Registration Closed');
define('index_precio', 'Price');
define('index_regresamos', "We'll be back...");
define('index_dollar_hoy', 'US Dollar Exchange rate');

?>