<?php 

define('menu','Menu');
define('index_inicio','Inicio');
define('index_campeonato','Campeonato');
define('index_reglamento','Reglamento');
define('index_registro','Registro');
define('index_solistas','Solistas');
define('index_parejas','Parejas');
define('index_grupos','Grupos');
define('index_envianostufoto','Envíanos tu foto');
define('index_lineup','Line Up');
define('index_comprartickets','Comprar Pases');
define('index_contactoviawhatsapp','Contacto vía Whatsapp');
define('index_eurosonlatinopresenta','Euroson Latino presenta');
define('index_fechaevento','Diciembre 6-11, 2021');
define('index_competencias_shows_workshops','Campeonato Mundial | Shows | Workshops | Concerts | Salsa & Bachata Social Parties');
define('index_transmision_en_vivo','Grand Oasis Cancún - México');
define('index_se_parte_de_la_historia','¡Ven y se parte de la historia!');
define('index_cuentaregresiva','Cuenta regresiva');
define('index_ver_mas','Ver más');
define('index_workshops','Workshops');
define('index_fullpass','Full Pass');
define('index_nightpass','Night Pass');
define('index_10_workshops','Workshops');
define('index_6_dias_competencia','días de competencia');
define('index_comprar_ticket','Comprar Pase');
define('index_apartar_ticket','Apartar Pase');
define('index_todos_los_derechos_reservados','Todos los derechos reservados ');
define('index_registro_solistas','Registro Solistas');
define('index_nombre','Nombre');
define('index_ingresa_tu_nombre','Ingresa tu nombre');
define('index_apellidos','Apellidos');
define('index_ingresa_tus_apellidos','Ingresa tus apellidos');
define('index_hotelnum','Código de reservación de hotel');
define('index_ingresa_hotelnum','Ingresa el código de reservación');
define('index_correo_electronico','Correo electrónico');
define('index_ingresa_tu_correo_electronico','Ingresa tu correo electrónico');
define('index_fecha_de_nacimiento','Fecha de nacimiento');
define('index_genero','Género');
define('index_masculino','Masculino');
define('index_femenino','Femenino');
define('index_pais','País');
define('index_seleccione_su_pais','Seleccione su país');
define('index_categoria','Categoría');
define('index_subtotal','Subtotal');
define('index_descuento','Descuento');
define('index_impuestos','Impuestos');
define('index_total','Total');
define('index_metodo_de_pago','Método de pago');
define('index_pago','Pago');
define('index_ya_realizaste_tu_pago','Pago con transferencia bancaria');
define('index_ingrese_su_id_de_transaccion','Ingrese número de referencia, número de autorización bancaria');
define('index_enviar_registro','Enviar registro');
define('index_informacion_competidor','Información competidor');
define('index_informacion_general','Información general');
define('index_nombre_del_grupo','Nombre del grupo');
define('index_nombre_del_representante','Nombre del representante');
define('index_no_telefonico','No. Telefónico');
define('index_no_de_integrantes','No. De integrantes');
define('index_informacion_de_integrantes','Información de integrantes');
define('index_todas_las_fotografias_enviadas','Todas las fotografías enviadas serán cargadas al <a href="https://facebook.com/eurosonlatino" target="_blank"> Facebook (Euroson Latino World Salsa Championship)</a>');
define('index_codigo_de_inscripcion','Código de inscripción');
define('index_tipo_de_categoria','Tipo de categoría');
define('index_arrastra_y_suleta_aqui_tu_archivo_para_subir','Arrastre y suelte aquí su archivo para subir');
define('index_o_selecciona_tu_archivo','O seleccionar archivo');
define('index_nota_importante_el_codigo_de_inscripcion','El código de inscripción lo tienes que haber recibido vía correo electrónico después de realizar tu registro. Si no has recibido tu código de inscripción y ya realizaste tu registro contáctanos info@eurosonlatino.com.mx o vía Whatsapp');
define('index_enviar_imagen','Enviar imagen');
define('index_programa','Programa');
define('index_y','y');
define('index_dias','Días');
define('index_horas','Horas');
define('index_mins','Mins');
define('index_segs','Segs');
define('index_ingresar_nombre_grupo','Ingresar el nombre del grupo');
define('index_invitados_internacionales','Invitados Internacionales');
define('index_tiene_cupon','¿Tienes un CUPÓN DE DESCUENTO?');
define('index_agregar_cupon','Click aquí para agregar cupón');
define('index_informacion_adicional','Información adicional');
define('index_notas_de_orden','Notas de orden');
define('index_placeholder_notas_orden','Notas sobre su pedido, p. Ej. notas especiales de la compra.');
define('index_comprar','Comprar');
define('index_alert_success_registro','<p class=""card-text font-size-sm"">En breve recibirás un correo electrónico con los detalles de tu registro, no olvides verificar tu bandeja de correos no deseados, spam u otros(En correos Outlook).</p>

<p class=""card-text font-size-sm""><strong>Si no lo recibiste 48hrs después de la compra, verifica tu bandeja de correos no deseados, spam u otros(En correos Outlook).</strong></p>

<p class=""card-text font-size-sm"">En caso de no haberlo recibido favor de enviar un correo a <a href=""mailto:info@eurosonlatino.com.mx"">info@eurosonlatino.com.mx</a></p>');
define('index_alert_success_imagenenviada','Envio de imagen realizado con éxito!');
define('index_placeholder_ingresa_codinsc','Ingresa tu Código de inscripción');
define('index_notaimportante','Nota Importante');
define("index_texto_formenviarfoto","El código de inscripción lo tienes que haber recibido vía correo electrónico después de realizar tu registro. Si no has recibido tu código de inscripción y ya realizaste tu registro contáctanos <a href='mailto:info@eurosonlatino.com.mx'>info@eurosonlatino.com.mx</a> or <a target='_blank' class='text-warning' href='https://api.whatsapp.com/send?phone=522222501558&text=Hola%2C%20necesito%20mas%20informaci%C3%B3n.'>Whatsapp</a>");
define('index_envianostufoto_menu','Envianos tu foto');
define('index_codigocupon','Cupón');
define('index_realizar_pago','Realizar pago');
define('index_terminos_condiciones','Estoy de acuerdo con los <a href="https://bit.ly/terminos-y-condiciones-euroson-latino" target="_blank">términos y condiciones</a>');
define('index_aceptar_terminos_y_condiciones','Debe aceptar los acuerdos para continuar');
define('index_seleccione_su_categoria','Seleccione su categoría');
define('index_redireccion','<span class="text-muted font-size-xs">Esta página se redireccionará en <span id="testdiv"></span> segundos</span>');
define('index_codigoincorrecto','Código de inscripción incorrecto, favor de revisar la información.');
define('index_problemas_contactanos',' Si tiene problemas, favor de contáctarnos <a class="text-dark" href="mailto:info@eurosonlatino.com.mx" target="_blank">info@eurosonlatino.com.mx</a> o vía Whatsapp presionando click <a target="_blank" class="text-dark" href="https://api.whatsapp.com/send?phone=522222501558&text=Hola%2C%20necesito%20mas%20informaci%C3%B3n.">aquí</a>');
define('index_cuponpromocional','Código de cupón promocional');
define('index_aplicarcodigo','Aplicar código');
define('index_ingresa_tu_codigo','Ingresa tu código');
define('index_campo_requerido','Campo requerido');
define('index_seleccione_una_opcion','Seleccione una opción');
define('index_details','Detalles');
define('index_backgroundhome','bg-header-es');
define('index_detalles_registro','Detalle de registro');
define('index_horariolocal','Horario - Mexico City');
define('index_diciembre','Dic');
define('index_resultados','Resultados');
define('index_lunes','Lunes 14');
define('index_martes','Martes 15');
define('index_miercoles','Miércoles 16');
define('index_jueves','Jueves 17');
define('index_viernes','Viernes 18');
define('index_tickets', 'Tickets');
define('index_apartado_fullpass', 'Aparta tu Full Pass');
define('index_apartado_nightpass', 'Aparta tu Night Pass');
define('index_selection_fullpass','Seleccione cuantos full pass apartará');
define('index_info_fullpass','Información de su Full Pass');
define('index_selecionar','Seleccionar');
define('index_mensaje_asistentes', '<h4><strong><span class="text-danger">Nota importante:</span></strong>Todos los asistentes al Euroson Latino 2023, deberán estar hospedados en el Hotel Grand Oasis Cancún,
ya que por política del hotel no se le permitirá el uso de las instalaciones a personas externas.</h4>');
define('index_mensaje_asistentes_2','<strong><span class="text-danger">Nota importante:</span></strong>Todos los asistentes al Euroson Latino 2023, deberán estar hospedados en el Hotel Grand Oasis Cancún,
ya que por política del hotel no se le permitirá el uso de las instalaciones a personas externas.</h4>');
define('index_liquida_pase', 'Liquida tu pase');
define('index_ingresa_codconfirmacion', 'Ingresa tu Invoice ID');
define('index_validar_codigo','Validar código');
define('index_slide_0','slide-main-0-es.jpg');
define('index_slide_1','slide-main-1-es.jpg');
define('index_slide_2','slide-main-2-es.jpg');
define('index_registroreservacion','Registro Reservación');
define('index_fecha_entrada','Fecha de entrada');
define('index_fecha_salida','Fecha de salida');
define('index_num_habitaciones', 'No. de habitaciones');
define('index_num_huespedes', 'No. de huéspedes');
define('index_adjuntar_comprobante', 'Adjuntar comprobante  de reservación');
define('index_mensaje_input_comprobante', 'Favor de adjuntar comprobante de su reservación de hotel');
define('index_adjuntar_archivo', 'Adjuntar archivo');
define('index_mensaje_input_archivo', 'Favor de adjuntar su archivo');
define('index_conciertos','Conciertos');
define('index_codconfirmfullpass', 'Código de confirmación de Full Pass');
define('index_ingresacodconfirmfullpass', 'Ingresar su código de confirmación de Full Pass');
define('index_infoapartado', 'Información del apartado');
define('index_nombrecompleto', 'Nombre completo');
define('index_expositores','Expositores');
define('index_desc_fullpass', 'Campeonato Mundial, Shows Internacionales, Conciertos, Workshops, Sociales Salsa, Bachata y Kizomba, Beach Club');
define('index_desc_nightpass', 'Campeonato Mundial, Shows Internacionales, Conciertos, Sociales Salsa, Bachata y Kizomba, Beach Club');
define('index_registro_cerrado', 'Inscripciones Cerradas');
define('index_precio', 'Precio');
define('index_regresamos', 'Volvemos en un momento...');
define('index_dollar_hoy', 'Dollar USA hoy');
?>